baseURL = 'https://ychen878.github.io'
languageCode = 'en-us'
title = 'Yi Chen'
theme = 'simple'

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Notes"
url = "/notes/"
weight = 2
[[menu.main]]
name = "Publications"
url = "/publications/"
weight = 3
[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 4
[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 5
