baseURL = 'https://ychen878.github.io'
locale = 'en-us'
title = 'Yi Chen'
theme = 'simple'

[security]
allowContent = ['^text/.*$']

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Notes"
url = "/notes/"
weight = 2
[[menu.main]]
name = "Algorithms"
url = "/categories/algorithms/"
weight = 3
[[menu.main]]
name = "Publications"
url = "/publications/"
weight = 4
[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 5
