#+TITLE:
#+AUTHOR:

* Building a model
Designing a simple Bayesian model benefits from a design loop with 3 steps:
1. Data story: Motivate the model by narrating how the data might arise.
2. Update: Educate your model by feeding it the data.
3. Evaluate: All statistical models require supervision, leading to model revision.
** Data story
Bayesian data analysis usually means producing a story for how the data came to be.
Such a story may be descriptive, i.e. it specifies associations that can be used
to predict outcomes, given observations.
Or it may be causal, a theory of how some events produce other events.
You can motivate your data story by trying to explain how each piece of data is
born.
** Update
A Bayesian model begins with one set of plausibilities assigned to each possible
parameters. These are the prior plausibilities. Then, it
updates them in light of the data, to produce the posterior plausibilities. This
updating process is a kind of learning, called Bayesian updating.
** Evaluate
The model's certainty is no guarantee that the model is a good one. Models of
all sorts can be very confident about an inference, even when the model is
seriously misleading.
* Components of the model
